import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const translations = {
  en: {
    // Navigation & Layout
    nav: {
      dashboard: 'Dashboard',
      reviews: 'Reviews',
      analytics: 'Analytics',
      locations: 'Locations',
      competitors: 'Competitors',
      settings: 'Settings',
      logout: 'Logout',
    },
    header: {
      title: 'Control your reputation in one place',
      subtitle: 'Revi tracks reviews, summarizes customer sentiment, and highlights the exact moments that need your attention.',
      reputationCenter: 'Reputation command center',
      addLocation: '+ Add location',
    },
    // Authentication
    auth: {
      loginTitle: 'Welcome back',
      loginSub: 'Sign in to manage your business reputation',
      registerTitle: 'Create an account',
      registerSub: 'Start tracking reviews and boosting ratings today',
      email: 'Email address',
      password: 'Password',
      name: 'Full Name',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      or: 'or',
      validationError: 'Please fill in all fields correctly',
    },
    // Onboarding
    onboarding: {
      title: 'Welcome to Revi',
      subtitle: 'Let\'s set up your business profile to start monitoring reviews.',
      businessName: 'Business Name',
      businessNamePl: 'e.g., Coffee Boom',
      locationName: 'Location Name',
      locationNamePl: 'e.g., Mega Park Branch',
      googleId: 'Google Place ID (Optional)',
      twoGisId: '2GIS Branch ID (Optional)',
      yandexId: 'Yandex Organization ID (Optional)',
      avitoUrl: 'Avito URL (Optional)',
      continue: 'Continue',
      back: 'Back',
      stepInfo: 'Step {{current}} of {{total}}',
    },
    // Dashboard
    dashboard: {
      reputationScore: 'Reputation Score',
      aiSummary: 'AI Summary',
      urgent: 'Urgent',
      urgentSub: 'reviews waiting for reply',
      openInbox: 'Open inbox',
      recentChanges: 'Recent changes',
      recentChangesSub: 'What shifted in the last seven days',
      platformShare: 'Platform share',
      platformShareSub: 'Where your reviews are coming from',
      recentReviews: 'Recent reviews',
      recentReviewsSub: 'Latest client feedback across platforms',
      reviewsMonitored: 'reviews under monitoring',
      reviewsMonitoredSub: 'All connected platforms feed into one inbox',
      waitingReply: 'reviews waiting for reply',
      waitingReplySub: 'Focus on unanswered conversations now',
      ratingTrend: 'Rating trend',
      ratingTrendSub: 'Compared with the previous weekly slice',
      noReviews: 'No reviews yet. Connect locations to start receiving reputation signals.',
      sentimentAware: 'Sentiment-aware',
      autoPrioritized: 'Auto-prioritized',
      replyReady: 'Reply-ready',
      live: 'LIVE',
    },
    // Reviews & Detail
    reviews: {
      title: 'Review Inbox',
      subtitle: 'Manage and reply to all customer feedback in real-time.',
      search: 'Search reviews...',
      filterAll: 'All Platforms',
      filterReplied: 'All Statuses',
      replied: 'Replied',
      unanswered: 'Unanswered',
      sentiment: 'Sentiment',
      rating: 'Rating',
      empty: 'No reviews found matching filters.',
      timeAgo: '{{count}}d ago',
      today: 'Today',
      yesterday: 'Yesterday',
      reply: 'Reply',
      viewDetail: 'View Detail',
      aiResponse: 'AI Response',
      generate: 'Generate Reply',
      send: 'Send Reply',
      sentSuccess: 'Reply posted successfully!',
      draft: 'Draft reply...',
      generating: 'Generating AI reply...',
      styleFriendly: 'Friendly',
      styleFormal: 'Formal',
      styleEmpathetic: 'Empathetic',
      replyTone: 'Reply Tone',
    },
    // Analytics
    analytics: {
      title: 'Reputation Analytics',
      subtitle: 'Analyze sentiment, ratings, and performance trends over time.',
      totalReviews: 'Total Reviews',
      avgRating: 'Average Rating',
      positiveSentiment: 'Positive Sentiment',
      reviewsTrend: 'Reviews & Rating Trend',
      sentimentOverTime: 'Sentiment Distribution Over Time',
      platformDistribution: 'Platform Breakdown',
    },
    // Locations
    locations: {
      title: 'Locations & Integrations',
      subtitle: 'Manage your physical branches and connect review sources.',
      addLocation: 'Add Location',
      editLocation: 'Edit Location',
      name: 'Location Name',
      connected: 'Connected',
      notConnected: 'Not connected',
      connect: 'Connect',
      disconnect: 'Disconnect',
      deleteConfirm: 'Are you sure you want to delete this location?',
      syncing: 'Syncing...',
      syncNow: 'Sync Now',
      lastSync: 'Last synced: {{time}}',
      neverSynced: 'Never synced',
    },
    // Competitors
    competitors: {
      title: 'Competitor Intelligence',
      subtitle: 'Track competitor ratings, review volume, and customer sentiment.',
      addCompetitor: 'Add Competitor',
      name: 'Competitor Name',
      rating: 'Rating',
      reviewsCount: 'Reviews Count',
      strength: 'Key Strength',
      weakness: 'Key Weakness',
      noCompetitors: 'No competitors added yet. Compare your performance now.',
    },
    // Settings
    settings: {
      title: 'Settings',
      subtitle: 'Manage your account settings, profile, and notification rules.',
      profileSection: 'Profile Details',
      name: 'Your Name',
      email: 'Email address',
      notifications: 'Notification Preferences',
      notifyTelegram: 'Notify in Telegram',
      notifyEmail: 'Notify via Email',
      notifyNewReviews: 'Alert on new reviews',
      notifyNegativeOnly: 'Only negative reviews (< 4 stars)',
      save: 'Save Settings',
      savedSuccess: 'Settings saved successfully!',
    },
  },
  ru: {
    // Навигация и разметка
    nav: {
      dashboard: 'Панель',
      reviews: 'Отзывы',
      analytics: 'Аналитика',
      locations: 'Филиалы',
      competitors: 'Конкуренты',
      settings: 'Настройки',
      logout: 'Выйти',
    },
    header: {
      title: 'Управляйте репутацией в одном месте',
      subtitle: 'Revi отслеживает отзывы, анализирует тональность клиентов и выделяет ключевые моменты, требующие вашего внимания.',
      reputationCenter: 'Центр управления репутацией',
      addLocation: '+ Добавить филиал',
    },
    // Авторизация
    auth: {
      loginTitle: 'С возвращением',
      loginSub: 'Войдите в систему для управления репутацией бизнеса',
      registerTitle: 'Создать аккаунт',
      registerSub: 'Начните отслеживать отзывы и повышать рейтинги уже сегодня',
      email: 'Электронная почта',
      password: 'Пароль',
      name: 'Полное имя',
      signIn: 'Войти',
      signUp: 'Зарегистрироваться',
      noAccount: 'Нет аккаунта?',
      haveAccount: 'Уже есть аккаунт?',
      or: 'или',
      validationError: 'Пожалуйста, заполните все поля корректно',
    },
    // Онбординг
    onboarding: {
      title: 'Добро пожаловать в Revi',
      subtitle: 'Давайте настроим профиль вашего бизнеса для мониторинга отзывов.',
      businessName: 'Название бизнеса',
      businessNamePl: 'например, Coffee Boom',
      locationName: 'Название филиала',
      locationNamePl: 'например, Филиал Mega Park',
      googleId: 'Google Place ID (Опционально)',
      twoGisId: '2GIS Branch ID (Опционально)',
      yandexId: 'Yandex Organization ID (Опционально)',
      avitoUrl: 'Avito URL (Опционально)',
      continue: 'Продолжить',
      back: 'Назад',
      stepInfo: 'Шаг {{current}} из {{total}}',
    },
    // Панель (Dashboard)
    dashboard: {
      reputationScore: 'Индекс репутации',
      aiSummary: 'Сводка ИИ',
      urgent: 'Срочно',
      urgentSub: 'отзывов ждут ответа',
      openInbox: 'Открыть входящие',
      recentChanges: 'Недавние изменения',
      recentChangesSub: 'Что изменилось за последние 7 дней',
      platformShare: 'Доля платформ',
      platformShareSub: 'Откуда приходят ваши отзывы',
      recentReviews: 'Недавние отзывы',
      recentReviewsSub: 'Последняя обратная связь клиентов на платформах',
      reviewsMonitored: 'отзывов отслеживается',
      reviewsMonitoredSub: 'Все подключенные платформы поступают в один ящик',
      waitingReply: 'отзывов ждут ответа',
      waitingReplySub: 'Сфокусируйтесь на неотвеченных отзывах сейчас',
      ratingTrend: 'Тренд рейтинга',
      ratingTrendSub: 'По сравнению с предыдущей неделей',
      noReviews: 'Пока нет отзывов. Подключите филиалы, чтобы начать получать сигналы репутации.',
      sentimentAware: 'Анализ тональности',
      autoPrioritized: 'Авто-приоритет',
      replyReady: 'Готово к ответу',
      live: 'LIVE',
    },
    // Отзывы и детали
    reviews: {
      title: 'Входящие отзывы',
      subtitle: 'Управляйте и отвечайте на все отзывы клиентов в реальном времени.',
      search: 'Поиск отзывов...',
      filterAll: 'Все платформы',
      filterReplied: 'Все статусы',
      replied: 'Отвеченные',
      unanswered: 'Неотвеченные',
      sentiment: 'Тональность',
      rating: 'Рейтинг',
      empty: 'Отзывы по выбранным фильтрам не найдены.',
      timeAgo: '{{count}} дн. назад',
      today: 'Сегодня',
      yesterday: 'Вчера',
      reply: 'Ответить',
      viewDetail: 'Подробнее',
      aiResponse: 'Ответ ИИ',
      generate: 'Создать ответ',
      send: 'Отправить ответ',
      sentSuccess: 'Ответ успешно опубликован!',
      draft: 'Текст ответа...',
      generating: 'Генерация ответа ИИ...',
      styleFriendly: 'Дружелюбный',
      styleFormal: 'Официальный',
      styleEmpathetic: 'Эмпатичный',
      replyTone: 'Тон ответа',
    },
    // Аналитика
    analytics: {
      title: 'Аналитика репутации',
      subtitle: 'Анализируйте тональность, рейтинги и тренды эффективности.',
      totalReviews: 'Всего отзывов',
      avgRating: 'Средний рейтинг',
      positiveSentiment: 'Положительные отзывы',
      reviewsTrend: 'Тренд отзывов и рейтинга',
      sentimentOverTime: 'Распределение тональности во времени',
      platformDistribution: 'Статистика по платформам',
    },
    // Филиалы (Locations)
    locations: {
      title: 'Филиалы и интеграции',
      subtitle: 'Управляйте филиалами вашей компании и подключайте источники отзывов.',
      addLocation: 'Добавить филиал',
      editLocation: 'Изменить филиал',
      name: 'Название филиала',
      connected: 'Подключено',
      notConnected: 'Не подключено',
      connect: 'Подключить',
      disconnect: 'Отключить',
      deleteConfirm: 'Вы уверены, что хотите удалить этот филиал?',
      syncing: 'Синхронизация...',
      syncNow: 'Синхронизировать',
      lastSync: 'Синхронизировано: {{time}}',
      neverSynced: 'Ни разу не синхронизировалось',
    },
    // Конкуренты (Competitors)
    competitors: {
      title: 'Анализ конкурентов',
      subtitle: 'Отслеживайте рейтинги, объемы отзывов и тональность конкурентов.',
      addCompetitor: 'Добавить конкурента',
      name: 'Название конкурента',
      rating: 'Рейтинг',
      reviewsCount: 'Кол-во отзывов',
      strength: 'Сильная сторона',
      weakness: 'Слабая сторона',
      noCompetitors: 'Конкуренты еще не добавлены. Сравните показатели прямо сейчас.',
    },
    // Настройки (Settings)
    settings: {
      title: 'Настройки',
      subtitle: 'Управляйте параметрами аккаунта, профиля и уведомлениями.',
      profileSection: 'Детали профиля',
      name: 'Ваше имя',
      email: 'Электронная почта',
      notifications: 'Настройки уведомлений',
      notifyTelegram: 'Уведомлять в Telegram',
      notifyEmail: 'Уведомлять по электронной почте',
      notifyNewReviews: 'Оповещать о новых отзывах',
      notifyNegativeOnly: 'Только о негативных (< 4 звезд)',
      save: 'Сохранить настройки',
      savedSuccess: 'Настройки успешно сохранены!',
    },
  },
  kk: {
    // Навигация және орналасу
    nav: {
      dashboard: 'Бақылау тақтасы',
      reviews: 'Пікірлер',
      analytics: 'Аналитика',
      locations: 'Филиалдар',
      competitors: 'Бәсекелестер',
      settings: 'Баптаулар',
      logout: 'Шығу',
    },
    header: {
      title: 'Бизнес беделін бір жерде басқарыңыз',
      subtitle: 'Revi пікірлерді қадағалайды, клиенттердің көңіл-күйін талдайды және назар аударуды қажет ететін сәттерді анықтайды.',
      reputationCenter: 'Беделді басқару орталығы',
      addLocation: '+ Филиал қосу',
    },
    // Авторизация
    auth: {
      loginTitle: 'Қош келдіңіз',
      loginSub: 'Бизнес беделін басқару үшін жүйеге кіріңіз',
      registerTitle: 'Тіркелу',
      registerSub: 'Бүгіннен бастап пікірлерді бақылап, рейтингтерді көтеріңіз',
      email: 'Электрондық пошта',
      password: 'Құпия сөз',
      name: 'Толық аты-жөніңіз',
      signIn: 'Кіру',
      signUp: 'Тіркелу',
      noAccount: 'Тіркелмегенсіз бе?',
      haveAccount: 'Тіркелгенсіз бе?',
      or: 'немесе',
      validationError: 'Барлық өрістерді дұрыс толтырыңыз',
    },
    // Онбординг
    onboarding: {
      title: 'Revi-ге қош келдіңіз',
      subtitle: 'Пікірлерді бақылауды бастау үшін бизнес профиліңізді реттейік.',
      businessName: 'Бизнес атауы',
      businessNamePl: 'мысалы, Coffee Boom',
      locationName: 'Филиал атауы',
      locationNamePl: 'мысалы, Mega Park филиалы',
      googleId: 'Google Place ID (Міндетті емес)',
      twoGisId: '2GIS Branch ID (Міндетті емес)',
      yandexId: 'Yandex Organization ID (Міндетті емес)',
      avitoUrl: 'Avito сілтемесі (Міндетті емес)',
      continue: 'Жалғастыру',
      back: 'Артқа',
      stepInfo: '{{total}} қадамның {{current}} қадамы',
    },
    // Бақылау тақтасы
    dashboard: {
      reputationScore: 'Бедел индексі',
      aiSummary: 'ЖИ жиынтығы',
      urgent: 'Шұғыл',
      urgentSub: 'жауап күтетін пікірлер',
      openInbox: 'Кіріс жәшігін ашу',
      recentChanges: 'Соңғы өзгерістер',
      recentChangesSub: 'Соңғы 7 күнде не өзгерді',
      platformShare: 'Платформалар үлесі',
      platformShareSub: 'Пікірлердің қайдан келетіндігі',
      recentReviews: 'Соңғы пікірлер',
      recentReviewsSub: 'Платформалардағы тұтынушылардың соңғы пікірлері',
      reviewsMonitored: 'пікір бақылануда',
      reviewsMonitoredSub: 'Барлық қосылған платформалар бір кіріс жәшігіне түседі',
      waitingReply: 'пікір жауап күтуде',
      waitingReplySub: 'Қазір жауап берілмеген пікірлерге назар аударыңыз',
      ratingTrend: 'Рейтинг тренді',
      ratingTrendSub: 'Өткен аптамен салыстырғанда',
      noReviews: 'Пікірлер әлі жоқ. Бедел белгілерін алу үшін филиалдарды қосыңыз.',
      sentimentAware: 'Көңіл-күйді талдау',
      autoPrioritized: 'Авто-басымдық',
      replyReady: 'Жауапқа дайын',
      live: 'LIVE',
    },
    // Отзывы және Толық мәліметтер
    reviews: {
      title: 'Кіріс пікірлер',
      subtitle: 'Тұтынушылардың барлық пікірлерін нақты уақытта басқарыңыз және жауап беріңіз.',
      search: 'Пікірлерді іздеу...',
      filterAll: 'Барлық платформалар',
      filterReplied: 'Барлық күйлер',
      replied: 'Жауап берілген',
      unanswered: 'Жауапсыз',
      sentiment: 'Көңіл-күй',
      rating: 'Рейтинг',
      empty: 'Таңдалған сүзгілерге сәйкес пікірлер табылмады.',
      timeAgo: '{{count}} күн бұрын',
      today: 'Бүгін',
      yesterday: 'Кеше',
      reply: 'Жауап беру',
      viewDetail: 'Толығырақ',
      aiResponse: 'ЖИ жауабы',
      generate: 'Жауап дайындау',
      send: 'Жауапты жіберу',
      sentSuccess: 'Жауап сәтті жарияланды!',
      draft: 'Жауап мәтіні...',
      generating: 'ЖИ жауабы әзірленуде...',
      styleFriendly: 'Достық',
      styleFormal: 'Ресми',
      styleEmpathetic: 'Эмпатикалық',
      replyTone: 'Жауап тоны',
    },
    // Аналитика
    analytics: {
      title: 'Бедел аналитикасы',
      subtitle: 'Уақыт өте келе көңіл-күйді, рейтингтерді және тиімділік трендтерін талдаңыз.',
      totalReviews: 'Барлық пікірлер',
      avgRating: 'Орташа рейтинг',
      positiveSentiment: 'Жағымды көңіл-күй',
      reviewsTrend: 'Пікірлер мен рейтинг тренді',
      sentimentOverTime: 'Көңіл-күйдің уақыт бойынша таралуы',
      platformDistribution: 'Платформалар бойынша бөлініс',
    },
    // Филиалдар
    locations: {
      title: 'Филиалдар мен интеграциялар',
      subtitle: 'Филиалдарды басқарыңыз және пікірлер көздерін қосыңыз.',
      addLocation: 'Филиалды қосу',
      editLocation: 'Филиалды өзгерту',
      name: 'Филиал атауы',
      connected: 'Қосылған',
      notConnected: 'Қосылмаған',
      connect: 'Қосу',
      disconnect: 'Ажырату',
      deleteConfirm: 'Бұл филиалды өшіруді қалайсыз ба?',
      syncing: 'Синхрондалуда...',
      syncNow: 'Синхрондау',
      lastSync: 'Синхрондалды: {{time}}',
      neverSynced: 'Синхрондалмаған',
    },
    // Бәсекелестер
    competitors: {
      title: 'Бәсекелестер талдауы',
      subtitle: 'Бәсекелестердің рейтингін, пікірлер көлемін және көңіл-күйін қадағалаңыз.',
      addCompetitor: 'Бәсекелесті қосу',
      name: 'Бәсекелес атауы',
      rating: 'Рейтинг',
      reviewsCount: 'Пікірлер саны',
      strength: 'Мықты жағы',
      weakness: 'Әлсіз жағы',
      noCompetitors: 'Бәсекелестер әлі қосылмаған. Салыстыруды қазір бастаңыз.',
    },
    // Баптаулар (Settings)
    settings: {
      title: 'Баптаулар',
      subtitle: 'Профиль баптауларын және хабарландыруларды басқарыңыз.',
      profileSection: 'Профиль мәліметтері',
      name: 'Атыңыз',
      email: 'Электрондық пошта',
      notifications: 'Хабарландырулар параметрлері',
      notifyTelegram: 'Telegram арқылы хабарлау',
      notifyEmail: 'Пошта арқылы хабарлау',
      notifyNewReviews: 'Жаңа пікірлер туралы ескерту',
      notifyNegativeOnly: 'Тек жағымсыз пікірлер (< 4 жұлдыз)',
      save: 'Баптауларды сақтау',
      savedSuccess: 'Баптаулар сәтті сақталды!',
    },
  },
}

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      language: 'ru',

      setLanguage: (language) => set({ language }),

      t: (keyPath, replacements = {}) => {
        const lang = get().language
        const keys = keyPath.split('.')
        let value = translations[lang]

        for (const key of keys) {
          if (!value || typeof value !== 'object') return keyPath
          value = value[key]
        }

        if (typeof value !== 'string') return keyPath

        let result = value
        for (const [k, v] of Object.entries(replacements)) {
          result = result.replace(new RegExp(`{{${k}}}`, 'g'), v)
        }

        return result
      },
    }),
    {
      name: 'language',
    }
  )
)
